# Generated by Django 3.1.7 on 2021-02-19 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210219_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients_for_recipe',
            old_name='created',
            new_name='date_pub',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='created',
            new_name='date_pub',
        ),
    ]
