# Generated by Django 3.1.7 on 2021-03-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210316_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.PositiveIntegerField(help_text='в минутах', verbose_name='Время приготовления'),
        ),
    ]
