# Generated by Django 3.1.7 on 2021-02-28 19:04

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20210224_0732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='unit',
            new_name='dimension',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин')], default='breakfast', max_length=22, verbose_name='Теги'),
        ),
    ]
