
# Generated by Django 3.1.7 on 2021-03-14 19:50


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipes.Ingredients_for_recipe', to='recipes.Ingredients', verbose_name='Ингредиенты'),
        ),
    ]
