# Generated by Django 3.1.7 on 2021-03-25 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20210319_0247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientsforrecipe',
            options={'verbose_name': 'Ингредиент для рецепта', 'verbose_name_plural': 'Ингредиенты для рецепта'},
        ),
        migrations.AlterField(
            model_name='ingredientsforrecipe',
            name='amount',
            field=models.PositiveIntegerField(default=1, help_text='в граммах', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
